image: alpine:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

build:
  stage: build
  image: mcr.microsoft.com/dotnet/core/sdk:2.2-alpine
  tags:
    - docker
  services:
  - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    GENERATOR__JSONSCHEMALICENSE: $CI_APPLICATION_REPOSITORY
  script:
    - install_dependencies
    - build
  only:
    - branches
    - tags
  # except:
  #   - master
  #   - production
  #   - preproduction

test:
  stage: test
  image: mcr.microsoft.com/dotnet/core/sdk:2.2-alpine
  tags:
    - docker
  script:
    - install_dependencies
    - test
  only:
    - branches
    - tags

.auto_devops: &auto_devops |
  [[ "$TRACE" ]] && set -x
  export CI_APPLICATION_TAG=$CI_COMMIT_SHA
  
  export TAG=$CI_APPLICATION_TAG
  export GENERATOR_JSONSCHEMALICENSE="$GENERATOR_JSONSCHEMALICENSE"

  function install_dependencies() {
    echo "Installing deps"
    apk add -U openssl curl tar gzip bash ca-certificates git
  }

  function build() {
    echo "Building..."
    dotnet build ./Conizi.Model.sln --configuration NetCore -f netstandard2.0
  }
  
  function test() {
    echo "Testing..."
    dotnet test ./test/Conizi.Model.UnitTests/Conizi.Model.UnitTests.csproj --filter "Category=UnitTest" -v n 
  }

before_script:
  - *auto_devops
