apiRules:
- exclude:
    uidRegex: ^System\.Object
    type: Type
- exclude:
    uidRegex: ^Conizi\.Model\.Core\.Converters
- include:
    uidRegex: ^Conizi\.Model\.Core\.Tools
- include:
    uidRegex: ^Conizi\.Model\.Core\.Entities
- exclude:
    uidRegex: ^Conizi\.Model\.Core
